name: Release and Update Homebrew

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout stock-price
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: echo "VERSION=$(cat VERSION | xargs)" >> $GITHUB_OUTPUT

      - name: Create Tag and Release
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          # Create or move the tag locally (-f is for force)
          git tag -f v$VERSION
          # Force push the tag to the remote (-f)
          git push origin v$VERSION -f
          # Create the release. 
          # Use --clobber to overwrite an existing release with the same tag.
          gh release create v$VERSION --title "v$VERSION" --generate-notes --clobber
  update-homebrew:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stock-price
        uses: actions/checkout@v4

      - name: Checkout homebrew-stock-change
        uses: actions/checkout@v4
        with:
          repository: artback/homebrew-stock-change
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Update Homebrew Formula
        run: |
          NEW_VERSION=${{ needs.create-release.outputs.version }}
          FORMULA_PATH="homebrew-tap/Formula/stock-price.rb"
          sed -i "s/version \".*\"/version \"$NEW_VERSION\"/" $FORMULA_PATH
          
          cd homebrew-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update stock-price to $NEW_VERSION"
          git push
